/* Numerical checks of this finite prototype, not a proof of all routes or device performance. */
const fs=require('fs'),path=require('path');
const R=path.resolve(__dirname,'..'),{GrappleSimulation}=require('../src/grapple-physics.js');
const config=JSON.parse(fs.readFileSync(path.join(R,'configs/grapple.json'))),scene=JSON.parse(fs.readFileSync(path.join(R,'scene.json')));
const out={testEnvironment:'Node '+process.version,date:new Date().toISOString(),scope:'Finite v04 numerical simulation only; no Phaser, no target-device measurements',checks:[]};
function check(name,test){try{const detail=test();out.checks.push({name,pass:true,detail});}catch(e){out.checks.push({name,pass:false,error:String(e)});}}
function assert(v,m){if(!v)throw Error(m);}
function fresh(){return new GrappleSimulation(config,scene);}
function runTrial(id,settings={},locked=false){const s=fresh();s.setElastic(settings);s.setLocked(locked);s.beginTrial(id);let peak=0,samples=[];for(let i=0;i<840;i++){s.step();let q=s.snapshot();peak=Math.max(peak,q.elastic.offset);if(i%60===0)samples.push({t:+q.time.toFixed(3),dx:q.elastic.dx,dy:q.elastic.dy,attached:q.player.attached});}return{s,peak,samples};}
check('Both canonical comparison trials land safely',()=>{const a=runTrial('beam'),b=runTrial('lantern');assert(a.s.metrics.rescues===0&&b.s.metrics.rescues===0,'trial needed rescue');assert(a.s.metrics.landings&&b.s.metrics.landings,'no landing');return{beam:a.s.events,lantern:b.s.events};});
check('Elastic load moves knot; locked comparison stays fixed',()=>{const a=runTrial('lantern'),b=runTrial('lantern',{},true);assert(a.peak>20,'insufficient driven displacement');assert(b.peak<1e-9,'locked pivot moved');return{elasticPeakPx:a.peak,lockedPeakPx:b.peak};});
check('Force-controlled rebound decays after release',()=>{const a=runTrial('lantern');const rest=a.s.snapshot().elastic.offset;assert(rest<a.peak*.01,'insufficient return');return{peakPx:a.peak,atSevenSecondsPx:rest,samples:a.samples};});
check('Releasing does not add a hidden launch impulse',()=>{const s=fresh();s.reset('lantern',true);for(let i=0;i<118;i++)s.step();let v=[s.player.vx,s.player.vy];s.release();assert(s.player.vx===v[0]&&s.player.vy===v[1],'velocity overwritten on release');return{before:v,after:[s.player.vx,s.player.vy]};});
check('Visible cable ends stay fixed and the knot equals physical anchor',()=>{const a=runTrial('lantern');const s=a.s;s.reset('lantern',true);for(let i=0;i<120;i++)s.step();let left=s.cablePoint(0),right=s.cablePoint(1),knot=s.cablePoint(s.elastic.attachT),an=s.elasticAnchor;assert(left.x===s.cable.x1&&left.y===s.cable.y1&&right.x===s.cable.x2&&right.y===s.cable.y2,'support moved');assert(Math.hypot(knot.x-an.x,knot.y-an.y)<1e-9,'knot detached');return{left,right,knot,physicalAnchor:{x:an.x,y:an.y}};});
check('Hand attachment matches rendered rope length while taut',()=>{const s=fresh();s.reset('lantern',true);let worst=0;for(let i=0;i<600;i++){s.step();const h=s.hand,a=s.anchor('lantern');worst=Math.max(worst,Math.max(0,Math.hypot(h.x-a.x,h.y-a.y)-s.player.ropeLength));}assert(worst<.05,'rope overstretch');return{maxStretchPx:worst};});
check('Fixed ticks agree under 30 / 60 / 144 Hz frame delivery',()=>{let values=[];for(const hz of [30,60,144]){let s=fresh();s.beginTrial('lantern');for(let i=0;i<hz*6;i++)s.advance(1/hz);values.push({hz,ticks:s.tick,x:s.player.x,y:s.player.y,anchorY:s.elasticAnchor.y});}let max=0;for(const v of values)max=Math.max(max,Math.abs(v.x-values[0].x),Math.abs(v.y-values[0].y),Math.abs(v.anchorY-values[0].anchorY));assert(max<1e-8,'refresh-dependent result');return{values,maxDifferencePx:max};});
check('Paused simulation ignores accumulated elapsed time',()=>{const s=fresh();s.beginTrial();for(let i=0;i<60;i++)s.step();const before=JSON.stringify(s.snapshot());s.paused=true;const hold=JSON.stringify(s.snapshot());s.advance(60);assert(hold===JSON.stringify(s.snapshot()),'paused state advanced');return{pausedForRequestedSeconds:60,tick:s.tick};});
check('Parameter extremes remain finite and respect offset cap',()=>{let cases=[];for(const stiffness of [28,140])for(const damping of [2,24])for(const maxOffset of [20,70]){const s=fresh();s.setElastic({stiffness,damping,maxOffset});s.reset('lantern',true);let maxRatio=0;for(let i=0;i<2400;i++){s.input.axis=Math.sin(i/117)>.4?1:-1;if(i%420===0)s.attach(s.station,false);if(i%420===290)s.release();if(i%360===20)s.jump();s.step();let a=s.elasticAnchor,e=s.elastic;maxRatio=Math.max(maxRatio,Math.hypot((a.x-a.restX)/(e.maxOffset*e.horizontalLimitRatio),(a.y-a.restY)/e.maxOffset));}assert(maxRatio<1.0001,'cap exceeded');cases.push({stiffness,damping,maxOffset,maxEllipseRatio:maxRatio,rescues:s.metrics.rescues,maxConstraintError:s.metrics.maxConstraintError});}return cases;});
check('Sample manual input reaches right landing',()=>{const trials=[];for(const hold of [1.10,1.15,1.20]){const s=fresh();s.input.axis=1;s.attach('lantern',true);let hit=null;for(let i=0;i<300;i++){if(i===Math.round(hold*120))s.release();s.step();if(s.player.ground==='finish'){hit={time:s.time,x:s.player.x,y:s.player.y};break;}}assert(hit,'failed sampled input '+hold);trials.push({hold,hit});}return{input:'From default lantern station, right held, jump+attach at t0, release at specified time; only these samples are checked',trials};});
out.passed=out.checks.filter(c=>c.pass).length;out.failed=out.checks.length-out.passed;fs.writeFileSync(path.join(R,'qa/physics-tests.json'),JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2));if(out.failed)process.exitCode=1;
