import type { StageName } from '../schemas/index.js';
import { StateTransitionAuditSchema, StateTransitionRecordSchema, type StateTransitionRecord } from '../schemas/state-transition.js';

export const MAX_FIX_ATTEMPTS = 2;
const transitions: Partial<Record<StageName, StageName[]>> = {
  CREATED: ['BUSINESS_PREFLIGHT', 'PRODUCTION_LINE_REVIEW', 'REFERENCE_DEEP_RESEARCH', 'REFERENCE_MECHANIC_LOCK', 'COMPETITOR_RESEARCH', 'ACTION_EXPERIMENT_SPEC'],
  BUSINESS_PREFLIGHT: ['REFERENCE_DEEP_RESEARCH', 'REFERENCE_MECHANIC_LOCK', 'COMPETITOR_RESEARCH', 'COST_GATE', 'FAILED'],
  PRODUCTION_LINE_REVIEW: ['REFERENCE_DEEP_RESEARCH', 'OPEN_SOURCE_RESEARCH', 'FAILED'],
  COST_GATE: ['REFERENCE_DEEP_RESEARCH', 'REFERENCE_MECHANIC_LOCK', 'COMPETITOR_RESEARCH', 'PLATFORM_ADAPTER_QA', 'TARGET_PLATFORM_QA', 'RELEASE_CANDIDATE', 'FAILED', 'FIX'],
  REFERENCE_DEEP_RESEARCH: ['REFERENCE_MECHANIC_LOCK'],
  REFERENCE_MECHANIC_LOCK: ['WAITING_FOR_REFERENCE_APPROVAL'],
  WAITING_FOR_REFERENCE_APPROVAL: ['OPEN_SOURCE_RESEARCH', 'DESIGN_REJECTED'],
  COMPETITOR_RESEARCH: ['IDEA_GENERATION'], IDEA_GENERATION: ['LOW_COST_FILTER'],
  LOW_COST_FILTER: ['PROTOTYPE_SELECTION'], PROTOTYPE_SELECTION: ['BUILD_3_PROTOTYPES'], BUILD_3_PROTOTYPES: ['PLAYTEST_TOURNAMENT'],
  PLAYTEST_TOURNAMENT: ['WINNER_SELECTION'], WINNER_SELECTION: ['IDEA_GENERATION', 'WAITING_FOR_PROTOTYPE_APPROVAL', 'NO_PROTOTYPE_WINNER'],
  WAITING_FOR_PROTOTYPE_APPROVAL: ['OPEN_SOURCE_RESEARCH', 'DESIGN_REJECTED', 'PROTOTYPE_REVISION_REQUESTED'], OPEN_SOURCE_RESEARCH: ['IAA_REVIEW'], IAA_REVIEW: ['BLUEPRINT', 'ART_DIRECTIONS'],
  ACTION_EXPERIMENT_SPEC: ['BUILD_ACTION_PROTOTYPES'], BUILD_ACTION_PROTOTYPES: ['PLAYTEST_ACTION_PROTOTYPES'],
  PLAYTEST_ACTION_PROTOTYPES: ['WAITING_FOR_ACTION_APPROVAL'],
  WAITING_FOR_ACTION_APPROVAL: ['ACTION_EXPERIMENT_APPROVED', 'ACTION_EXPERIMENT_REFACTOR', 'ACTION_EXPERIMENT_KILLED'],
  ART_DIRECTIONS: ['WAITING_FOR_CODEX_IMAGEGEN', 'WAITING_FOR_ART_APPROVAL'],
  WAITING_FOR_CODEX_IMAGEGEN: ['ART_DIRECTIONS', 'ASSETS'],
  BLUEPRINT: ['EXPERIENCE_CONTRACT', 'EXPERIENCE_HYPOTHESIS', 'ART_DIRECTIONS'], EXPERIENCE_HYPOTHESIS: ['EXPERIENCE_CONTRACT', 'CORE_SPEC_FROZEN', 'ART_DIRECTIONS'], CORE_SPEC_FROZEN: ['FEEL_PROTOTYPE', 'NARRATIVE_CONTRACT', 'SYSTEMS_CONTRACT', 'PUZZLE_CONTRACT', 'ART_DIRECTIONS'],
  WAITING_FOR_ART_APPROVAL: ['STYLE_LOCK'], STYLE_LOCK: ['CONTENT_EXPANSION', 'ASSETS'], CONTENT_EXPANSION: ['UI_SKELETON', 'POLISH_VERTICAL_SLICE'], UI_SKELETON: ['POLISH_VERTICAL_SLICE', 'FULL_BUILD'], POLISH_VERTICAL_SLICE: ['FULL_BUILD'], ASSETS: ['FULL_BUILD'], FULL_BUILD: ['QA'], BUILD: ['QA'],
  EXPERIENCE_CONTRACT: ['FEEL_PROTOTYPE'], FEEL_PROTOTYPE: ['NATURAL_PLAY_QA'], NATURAL_PLAY_QA: ['EXPERIENCE_REVIEW'], EXPERIENCE_REVIEW: ['FEEL_REPAIR', 'CONTENT_EXPANSION', 'ART_DIRECTIONS'], FEEL_REPAIR: ['FEEL_PROTOTYPE'],
  NARRATIVE_CONTRACT: ['STORY_VERTICAL_SLICE'], STORY_VERTICAL_SLICE: ['CHOICE_CONSEQUENCE_QA'], CHOICE_CONSEQUENCE_QA: ['NARRATIVE_REVIEW'], NARRATIVE_REVIEW: ['REPLAY_VALUE_QA'], REPLAY_VALUE_QA: ['CONTENT_EXPANSION', 'ART_DIRECTIONS'],
  SYSTEMS_CONTRACT: ['SYSTEMS_PROTOTYPE'], SYSTEMS_PROTOTYPE: ['STRATEGY_QA'], STRATEGY_QA: ['PROGRESSION_REVIEW'], PROGRESSION_REVIEW: ['CONTENT_EXPANSION', 'ART_DIRECTIONS'],
  PUZZLE_CONTRACT: ['PUZZLE_PROTOTYPE'], PUZZLE_PROTOTYPE: ['PUZZLE_FAIRNESS_QA'], PUZZLE_FAIRNESS_QA: ['PUZZLE_REVIEW'], PUZZLE_REVIEW: ['CONTENT_EXPANSION', 'ART_DIRECTIONS'],
  QA: ['FIX', 'FINAL_PROFILE_QA', 'NORMAL_FLOW_QA', 'VISUAL_EVIDENCE_QA', 'CONTENT_VARIATION_QA', 'QUALITY_BASELINE_QA', 'PRESENTATION_QA', 'SUPPLY_CHAIN_QA', 'ORIGINALITY_REVIEW', 'CERTIFICATION', 'COST_GATE', 'PLATFORM_ADAPTER_QA', 'TARGET_PLATFORM_QA', 'RELEASE_CANDIDATE', 'WAITING_FOR_HUMAN_PLAYTEST', 'RELEASE'],
  FINAL_PROFILE_QA: ['NORMAL_FLOW_QA', 'VISUAL_EVIDENCE_QA', 'CONTENT_VARIATION_QA', 'QUALITY_BASELINE_QA', 'PRESENTATION_QA', 'SUPPLY_CHAIN_QA', 'ORIGINALITY_REVIEW', 'CERTIFICATION', 'COST_GATE', 'PLATFORM_ADAPTER_QA', 'TARGET_PLATFORM_QA', 'RELEASE_CANDIDATE', 'BLIND_PLAYTEST_QA', 'WAITING_FOR_HUMAN_PLAYTEST', 'FIX'],
  NORMAL_FLOW_QA: ['VISUAL_EVIDENCE_QA', 'CONTENT_VARIATION_QA', 'QUALITY_BASELINE_QA', 'PRESENTATION_QA', 'SUPPLY_CHAIN_QA', 'ORIGINALITY_REVIEW', 'CERTIFICATION', 'COST_GATE', 'PLATFORM_ADAPTER_QA', 'TARGET_PLATFORM_QA', 'RELEASE_CANDIDATE', 'FIX'],
  VISUAL_EVIDENCE_QA: ['CONTENT_VARIATION_QA', 'QUALITY_BASELINE_QA', 'PRESENTATION_QA', 'SUPPLY_CHAIN_QA', 'ORIGINALITY_REVIEW', 'CERTIFICATION', 'COST_GATE', 'PLATFORM_ADAPTER_QA', 'TARGET_PLATFORM_QA', 'RELEASE_CANDIDATE', 'WAITING_FOR_HUMAN_PLAYTEST', 'FIX'],
  PRESENTATION_QA: ['SUPPLY_CHAIN_QA', 'ORIGINALITY_REVIEW', 'CERTIFICATION', 'COST_GATE', 'PLATFORM_ADAPTER_QA', 'TARGET_PLATFORM_QA', 'RELEASE_CANDIDATE', 'WAITING_FOR_HUMAN_PLAYTEST', 'FIX'],
  SUPPLY_CHAIN_QA: ['ORIGINALITY_REVIEW', 'CERTIFICATION', 'COST_GATE', 'PLATFORM_ADAPTER_QA', 'TARGET_PLATFORM_QA', 'RELEASE_CANDIDATE', 'FIX'],
  CONTENT_VARIATION_QA: ['QUALITY_BASELINE_QA', 'PRESENTATION_QA', 'SUPPLY_CHAIN_QA', 'ORIGINALITY_REVIEW', 'CERTIFICATION', 'COST_GATE', 'PLATFORM_ADAPTER_QA', 'TARGET_PLATFORM_QA', 'RELEASE_CANDIDATE', 'WAITING_FOR_HUMAN_PLAYTEST', 'FIX'],
  QUALITY_BASELINE_QA: ['ORIGINALITY_REVIEW', 'CERTIFICATION', 'COST_GATE', 'PLATFORM_ADAPTER_QA', 'TARGET_PLATFORM_QA', 'RELEASE_CANDIDATE', 'WAITING_FOR_HUMAN_PLAYTEST', 'FIX'],
  ORIGINALITY_REVIEW: ['CERTIFICATION', 'COST_GATE', 'PLATFORM_ADAPTER_QA', 'TARGET_PLATFORM_QA', 'RELEASE_CANDIDATE', 'WAITING_FOR_HUMAN_PLAYTEST', 'FIX'],
  CERTIFICATION: ['COST_GATE', 'PLATFORM_ADAPTER_QA', 'TARGET_PLATFORM_QA', 'RELEASE_CANDIDATE', 'FIX'],
  PLATFORM_ADAPTER_QA: ['TARGET_PLATFORM_QA', 'RELEASE_CANDIDATE', 'FIX'],
  TARGET_PLATFORM_QA: ['RELEASE_CANDIDATE', 'FIX'],
  RELEASE_CANDIDATE: ['BLIND_PLAYTEST_QA', 'WAITING_FOR_HUMAN_PLAYTEST', 'QA', 'FIX'],
  BLIND_PLAYTEST_QA: ['WAITING_FOR_HUMAN_PLAYTEST', 'FIX'],
  WAITING_FOR_HUMAN_PLAYTEST: ['ACCEPTANCE_REVIEW', 'RELEASE', 'FIX'],
  ACCEPTANCE_REVIEW: ['RELEASE', 'FIX'],
  LAUNCH_METRICS: ['LIVE_MONITORING', 'LIVE_VERIFIED', 'ABANDONED'],
  RELEASE: ['FACTORY_EVAL', 'COMPLETED'],
  FACTORY_EVAL: ['COMPLETED', 'RELEASE'],
  LIVE_MONITORING: ['LIVE_VERIFIED', 'COMPLETED', 'ABANDONED'],
  LIVE_VERIFIED: ['COMPLETED', 'ABANDONED'],
  FIX: ['QA'],
};

export function canTransition(from: StageName, to: StageName, context: { fixAttempts?: number } = {}): boolean {
  if (to === 'FAILED') return from !== 'COMPLETED';
  if (to === 'ABANDONED') return from !== 'COMPLETED' && from !== 'ABANDONED';
  if (from === 'QA' && to === 'FIX' && (context.fixAttempts ?? 0) >= MAX_FIX_ATTEMPTS) return false;
  return transitions[from]?.includes(to) ?? false;
}

export type StageTransitionOptions = { plannedStages?: readonly StageName[]; fixAttempts?: number };

/** Evaluate a persisted transition without changing live state. Explicit
 * state-machine edges win; a forward jump is legal only when the immutable
 * pipeline plan contains both stages in order. */
export function evaluateStageTransition(from: StageName, to: StageName, options: StageTransitionOptions = {}) {
  if (from === to) return StateTransitionAuditSchema.parse({ passed: true, blockers: [] });
  if (canTransition(from, to, options)) return StateTransitionAuditSchema.parse({ passed: true, blockers: [] });
  if (['COMPLETED', 'ABANDONED', 'FAILED'].includes(to)) return StateTransitionAuditSchema.parse({ passed: true, blockers: [] });
  const planned = options.plannedStages ?? [];
  const fromIndex = planned.indexOf(from);
  const toIndex = planned.indexOf(to);
  if (fromIndex >= 0 && toIndex > fromIndex) return StateTransitionAuditSchema.parse({ passed: true, blockers: [] });
  return StateTransitionAuditSchema.parse({ passed: false, blockers: [`invalid-transition:${from}->${to}`] });
}

export function evaluateTransitionHistory(historyValue: readonly StateTransitionRecord[], options: StageTransitionOptions = {}) {
  const history = historyValue.map((item) => StateTransitionRecordSchema.parse(item));
  const blockers: string[] = [];
  history.forEach((item, index) => {
    if (index > 0 && history[index - 1]!.to !== item.from) blockers.push(`history-discontinuity:${index}`);
    const result = evaluateStageTransition(item.from, item.to, options);
    blockers.push(...result.blockers.map((blocker) => `${index}:${blocker}`));
  });
  return StateTransitionAuditSchema.parse({ passed: blockers.length === 0, blockers: [...new Set(blockers)] });
}
