import { readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { parse, stringify } from 'yaml';
import { ArtDirectorAgent, AssetProducerAgent, BuilderAgent, FixerAgent, ProducerAgent, QAAgent, ReleaseAgent, StyleLockAgent } from './agents/index.js';
import { createArtReview } from './core/art-review.js';
import { exists, listFiles, sha256Text } from './core/files.js';
import { FileRunStore } from './core/run-store.js';
import { MAX_FIX_ATTEMPTS } from './core/state-machine.js';
import { MockAgentProvider, MockCodexProvider, MockImageProvider } from './providers/mock.js';
import { OpenAIAgentProvider, OpenAICodexProvider, OpenAIImageProvider } from './providers/real.js';
import { LocalRuntimeProvider, MockQAProvider, PlaywrightQAProvider } from './providers/runtime-qa.js';
import { ArtApprovalSchema, ArtDirectionsSchema, AssetManifestSchema, GameBlueprintSchema, StyleLockSchema, type RunState, type StageName, type StageRecord } from './schemas/index.js';

export type FactoryOptions = { root?: string; repositoryRoot?: string; mode?: 'mock' | 'real'; qaMode?: 'stub' | 'playwright' };
export function createFactory(options: FactoryOptions = {}) {
  const repositoryRoot = options.repositoryRoot ?? process.cwd(); const root = options.root ?? repositoryRoot; const mode = options.mode ?? (process.env.FACTORY_PROVIDER_MODE === 'real' ? 'real' : 'mock'); const qaMode = options.qaMode ?? 'playwright';
  const store = new FileRunStore(root); const agents = mode === 'real' ? new OpenAIAgentProvider() : new MockAgentProvider(); const images = mode === 'real' ? new OpenAIImageProvider() : new MockImageProvider(); const codex = mode === 'real' ? new OpenAICodexProvider() : new MockCodexProvider(); const runtime = new LocalRuntimeProvider(repositoryRoot).runtime('web-lite'); const qaProvider = qaMode === 'playwright' ? new PlaywrightQAProvider() : new MockQAProvider();
  const producerAgent = new ProducerAgent(agents); const artDirectorAgent = new ArtDirectorAgent(agents); const styleLockAgent = new StyleLockAgent(agents); const assetProducerAgent = new AssetProducerAgent(images); const builderAgent = new BuilderAgent(codex, runtime); const qaAgent = new QAAgent(qaProvider, runtime); const fixerAgent = new FixerAgent(codex, runtime); const releaseAgent = new ReleaseAgent();

  async function begin(state: RunState, stage: StageName, inputArtifacts: string[]): Promise<StageRecord> { const record = store.record(stage, state.stages[stage]); record.inputArtifacts = inputArtifacts; state.stage = stage; state.status = 'running'; state.stages[stage] = record; await store.save(state); await store.log(state.runId, 'stage.started', { stage, attempt: record.attempts }); return record; }
  async function complete(state: RunState, record: StageRecord, outputs: string[], evidence: string[]) { record.status = 'completed'; record.finishedAt = new Date().toISOString(); record.outputArtifacts = outputs; record.evidence = evidence; state.status = 'running'; await store.save(state); await store.log(state.runId, 'stage.completed', { stage: record.stage, outputs, evidence }); }
  async function fail(state: RunState, record: StageRecord, error: unknown): Promise<never> { const message = error instanceof Error ? error.stack ?? error.message : String(error); record.status = 'failed'; record.finishedAt = new Date().toISOString(); record.errors.push(message); state.stage = 'FAILED'; state.status = 'failed'; await store.save(state); await store.log(state.runId, 'stage.failed', { stage: record.stage, message }); throw error; }
  function done(state: RunState, stage: StageName) { return state.stages[stage]?.status === 'completed'; }

  async function execute(runId: string): Promise<RunState> {
    const state = await store.load(runId); if (state.stage === 'COMPLETED') return state;
    const runRoot = store.runRoot(runId); const seed = await store.readSeedFile(path.join(runRoot, 'input/seed.yaml'));
    if (!done(state, 'BLUEPRINT')) { const record = await begin(state, 'BLUEPRINT', ['input/seed.yaml']); try { const value = await producerAgent.run(seed); await store.writeArtifact(runId, 'game-blueprint.json', value); await complete(state, record, ['artifacts/game-blueprint.json'], ['zod:GameBlueprintSchema']); } catch (error) { return fail(state, record, error); } }
    const blueprint = GameBlueprintSchema.parse(await store.readArtifact(runId, 'game-blueprint.json'));
    if (!done(state, 'ART_DIRECTIONS')) { const record = await begin(state, 'ART_DIRECTIONS', ['artifacts/game-blueprint.json']); try { const value = await artDirectorAgent.run(blueprint); await store.writeArtifact(runId, 'art-directions.json', value); await createArtReview(runRoot, blueprint, value); await complete(state, record, ['artifacts/art-directions.json', 'art-review/index.html', 'art-review/art-directions.json', 'human/art-approval.example.yaml'], ['zod:ArtDirectionsSchema', 'directions:4']); } catch (error) { return fail(state, record, error); } }
    const approvalFile = path.join(runRoot, 'human/art-approval.yaml');
    if (!await exists(approvalFile)) { const now = new Date().toISOString(); state.stage = 'WAITING_FOR_ART_APPROVAL'; state.status = 'waiting'; state.stages.WAITING_FOR_ART_APPROVAL = state.stages.WAITING_FOR_ART_APPROVAL ?? { stage: 'WAITING_FOR_ART_APPROVAL', status: 'waiting', startedAt: now, finishedAt: null, attempts: 1, inputArtifacts: ['artifacts/art-directions.json'], outputArtifacts: [], errors: [], evidence: ['human/art-approval.example.yaml'] }; await store.save(state); await store.log(runId, 'run.waiting', { gate: 'art-approval' }); return state; }
    if (!done(state, 'STYLE_LOCK')) { if (state.stages.WAITING_FOR_ART_APPROVAL) { state.stages.WAITING_FOR_ART_APPROVAL.status = 'completed'; state.stages.WAITING_FOR_ART_APPROVAL.finishedAt ??= new Date().toISOString(); state.stages.WAITING_FOR_ART_APPROVAL.outputArtifacts = ['human/art-approval.yaml']; } const record = await begin(state, 'STYLE_LOCK', ['artifacts/game-blueprint.json', 'artifacts/art-directions.json', 'human/art-approval.yaml']); try { const approval = ArtApprovalSchema.parse(parse(await readFile(approvalFile, 'utf8'))); const directions = ArtDirectionsSchema.parse(await store.readArtifact(runId, 'art-directions.json')); const value = await styleLockAgent.run(blueprint, directions, approval); await store.writeArtifact(runId, 'style-lock.json', value); await complete(state, record, ['artifacts/style-lock.json'], ['zod:StyleLockSchema', `selected:${value.directionId}`]); } catch (error) { return fail(state, record, error); } }
    const styleLock = StyleLockSchema.parse(await store.readArtifact(runId, 'style-lock.json'));
    if (!done(state, 'ASSETS')) { const record = await begin(state, 'ASSETS', ['artifacts/game-blueprint.json', 'artifacts/style-lock.json']); try { const value = await assetProducerAgent.run(path.join(runRoot, 'workspace/generated-assets'), blueprint, styleLock); await store.writeArtifact(runId, 'asset-manifest.json', value); await complete(state, record, ['artifacts/asset-manifest.json', 'workspace/generated-assets/'], ['zod:AssetManifestSchema', `assets:${value.assets.length}`]); } catch (error) { return fail(state, record, error); } }
    const assetManifest = AssetManifestSchema.parse(await store.readArtifact(runId, 'asset-manifest.json')); const workspace = path.join(runRoot, 'workspace/game');
    if (!done(state, 'BUILD')) { const record = await begin(state, 'BUILD', ['artifacts/game-blueprint.json', 'artifacts/style-lock.json', 'artifacts/asset-manifest.json', `templates/web-lite/${blueprint.template}`]); try { const result = await builderAgent.run(workspace, blueprint, styleLock, assetManifest, blueprint.template, path.join(runRoot, 'workspace/generated-assets')); state.codexThreadId = result.threadId; await store.writeArtifact(runId, 'build-report.json', result.report); await complete(state, record, ['artifacts/build-report.json', 'workspace/game/dist/'], ['vite:build-success', `files:${result.report.files.length}`]); } catch (error) { return fail(state, record, error); } }
    let qaPassed = false;
    while (!qaPassed) {
      const record = await begin(state, 'QA', ['artifacts/build-report.json', 'workspace/game/dist/']);
      try { const report = await qaAgent.run(workspace, runRoot); await writeFile(path.join(runRoot, 'logs/console.log'), qaMode === 'playwright' ? await readFile(path.join(runRoot, 'logs/console.log')) : 'stub QA\n'); await store.writeArtifact(runId, 'qa-report.json', report); await complete(state, record, ['artifacts/qa-report.json', 'logs/console.log', ...report.screenshots], [qaMode === 'playwright' ? 'playwright:completed' : 'qa:stub', `passed:${report.passed}`]); qaPassed = report.passed; if (!qaPassed) { if (state.fixAttempts >= MAX_FIX_ATTEMPTS) throw new Error(`QA failed after maximum ${MAX_FIX_ATTEMPTS} automatic fixes`); const fixRecord = await begin(state, 'FIX', ['artifacts/qa-report.json']); const fix = await fixerAgent.run(workspace, state.codexThreadId, report); state.codexThreadId = fix.threadId; state.fixAttempts += 1; await complete(state, fixRecord, ['workspace/game/dist/'], [`fix-attempt:${state.fixAttempts}`, fix.summary]); } } catch (error) { return fail(state, record, error); }
    }
    if (!done(state, 'RELEASE')) { const record = await begin(state, 'RELEASE', ['artifacts/game-blueprint.json', 'artifacts/build-report.json', 'artifacts/qa-report.json', 'workspace/game/dist/']); try { const manifest = await releaseAgent.run(runRoot, blueprint); await store.writeArtifact(runId, 'release-manifest.json', manifest); await complete(state, record, ['artifacts/release-manifest.json', 'release-candidate/'], [`release-files:${manifest.files.length}`, 'sha256:recorded']); } catch (error) { return fail(state, record, error); } }
    state.stage = 'COMPLETED'; state.status = 'completed'; state.stages.COMPLETED = { stage: 'COMPLETED', status: 'completed', startedAt: new Date().toISOString(), finishedAt: new Date().toISOString(), attempts: 1, inputArtifacts: ['release-candidate/'], outputArtifacts: ['release-candidate/release-manifest.json'], errors: [], evidence: ['pipeline:complete'] }; await store.save(state); await store.log(runId, 'run.completed', {}); return state;
  }

  return {
    validate: (seedFile: string) => store.readSeedFile(seedFile),
    async newRun(seedFile: string) { const seed = await store.readSeedFile(seedFile); const runId = `${new Date().toISOString().replace(/[-:.TZ]/g, '').slice(0, 14)}-${sha256Text(stringify(seed)).slice(0, 8)}`; let candidate = runId; let suffix = 1; while (await exists(store.runRoot(candidate))) candidate = `${runId}-${suffix++}`; await store.create(candidate, seedFile, mode); return candidate; },
    run: execute,
    async resume(runId: string) { const state = await store.load(runId); if (state.stage === 'WAITING_FOR_ART_APPROVAL' && !await exists(path.join(store.runRoot(runId), 'human/art-approval.yaml'))) return state; return execute(runId); },
    status: (runId: string) => store.load(runId),
    async inspect(runId: string) { const state = await store.load(runId); const artifacts = await listFiles(path.join(store.runRoot(runId), 'artifacts')); return { state, artifacts }; },
    async retry(runId: string, stage: StageName) { const state = await store.load(runId); if (state.stages[stage]) state.stages[stage].status = 'pending'; state.stage = stage; state.status = 'pending'; if (stage === 'QA') await rm(store.artifact(runId, 'qa-report.json'), { force: true }); await store.save(state); return execute(runId); },
    async demo(seedFile = path.join(repositoryRoot, 'examples/seeds/ghost-night-market.yaml')) { const runId = await this.newRun(seedFile); await execute(runId); const approval = path.join(store.runRoot(runId), 'human/art-approval.yaml'); await writeFile(approval, 'selected_direction: direction_b\nkeep: [character_proportion, overall_palette, ui_shape]\nchange: [reduce_saturation, simplify_background]\nnotes: [不要太像儿童游戏, UI要简洁, 图标要醒目]\n'); await execute(runId); return runId; },
  };
}
